package edu.harvard.channing.regepi.hibernate.test;
// default package
// Generated Oct 2, 2014 9:45:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "channingreview")
public class Attachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7490624254006334311L;
	private Integer attachmentid;
	private String email;
	private byte[] fileContent;
	private String fileName;
	private Long fileSize;
	private String fileType;
	private String manuscriptId;
	private String filePath;

	public Attachment() {
	}

	public Attachment(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	public Attachment(String email, byte[] fileContent, String fileName,
			Long fileSize, String fileType, String manuscriptId, String filePath) {
		this.email = email;
		this.fileContent = fileContent;
		this.fileName = fileName;
		this.fileSize = fileSize;
		this.fileType = fileType;
		this.manuscriptId = manuscriptId;
		this.filePath = filePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attachmentid", unique = true, nullable = false)
	public Integer getAttachmentid() {
		return this.attachmentid;
	}

	public void setAttachmentid(Integer attachmentid) {
		this.attachmentid = attachmentid;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "file_content")
	public byte[] getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_size")
	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "file_type")
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "manuscript_id", nullable = false)
	public String getManuscriptId() {
		return this.manuscriptId;
	}

	public void setManuscriptId(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	@Column(name = "file_path")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
