package edu.harvard.channing.regepi.hibernate.test;
// default package
// Generated Oct 2, 2014 9:45:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dataidform generated by hbm2java
 */
@Entity
@Table(name = "dataidform", catalog = "channingreview")
public class Dataidform implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6561747417894812843L;
	private Integer id;
	private String authors;
	private String code;
	private String programDirectory;
	private String email;
	private Date formDate;
	private String manuscriptId;
	private String radio;
	private String seniorAuthor;
	private String table1;
	private String table2;
	private String table3;
	private String table4;
	private String table5;
	private String title;
	private String userGroup;

	public Dataidform() {
	}

	public Dataidform(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	public Dataidform(String authors, String code, String programDirectory,
			String email, Date formDate, String manuscriptId, String radio,
			String seniorAuthor, String table1, String table2, String table3,
			String table4, String table5, String title, String userGroup) {
		this.authors = authors;
		this.code = code;
		this.programDirectory = programDirectory;
		this.email = email;
		this.formDate = formDate;
		this.manuscriptId = manuscriptId;
		this.radio = radio;
		this.seniorAuthor = seniorAuthor;
		this.table1 = table1;
		this.table2 = table2;
		this.table3 = table3;
		this.table4 = table4;
		this.table5 = table5;
		this.title = title;
		this.userGroup = userGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "authors")
	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "program_directory")
	public String getProgramDirectory() {
		return this.programDirectory;
	}

	public void setProgramDirectory(String programDirectory) {
		this.programDirectory = programDirectory;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "form_date", length = 19)
	public Date getFormDate() {
		return this.formDate;
	}

	public void setFormDate(Date formDate) {
		this.formDate = formDate;
	}

	@Column(name = "manuscript_id", nullable = false)
	public String getManuscriptId() {
		return this.manuscriptId;
	}

	public void setManuscriptId(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	@Column(name = "radio")
	public String getRadio() {
		return this.radio;
	}

	public void setRadio(String radio) {
		this.radio = radio;
	}

	@Column(name = "senior_author")
	public String getSeniorAuthor() {
		return this.seniorAuthor;
	}

	public void setSeniorAuthor(String seniorAuthor) {
		this.seniorAuthor = seniorAuthor;
	}

	@Column(name = "table1")
	public String getTable1() {
		return this.table1;
	}

	public void setTable1(String table1) {
		this.table1 = table1;
	}

	@Column(name = "table2")
	public String getTable2() {
		return this.table2;
	}

	public void setTable2(String table2) {
		this.table2 = table2;
	}

	@Column(name = "table3")
	public String getTable3() {
		return this.table3;
	}

	public void setTable3(String table3) {
		this.table3 = table3;
	}

	@Column(name = "table4")
	public String getTable4() {
		return this.table4;
	}

	public void setTable4(String table4) {
		this.table4 = table4;
	}

	@Column(name = "table5")
	public String getTable5() {
		return this.table5;
	}

	public void setTable5(String table5) {
		this.table5 = table5;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "user_group")
	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}

}
