package edu.harvard.channing.regepi.hibernate.test;
// default package
// Generated Oct 2, 2014 9:45:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reviewer generated by hbm2java
 */
@Entity
@Table(name = "reviewer", catalog = "channingreview")
public class Reviewer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2787914747562194991L;
	private Integer id;
	private String email;
	private String name;
	private String reviewerType;
	private String userGroup;

	public Reviewer() {
	}

	public Reviewer(String email, String name, String reviewerType,
			String userGroup) {
		this.email = email;
		this.name = name;
		this.reviewerType = reviewerType;
		this.userGroup = userGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "reviewer_type")
	public String getReviewerType() {
		return this.reviewerType;
	}

	public void setReviewerType(String reviewerType) {
		this.reviewerType = reviewerType;
	}

	@Column(name = "user_group")
	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}

}
