package edu.harvard.channing.regepi.hibernate.test;
// default package
// Generated Oct 2, 2014 9:45:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reviewinfo generated by hbm2java
 */
@Entity
@Table(name = "reviewinfo", catalog = "channingreview")
public class Reviewinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3085767255201020358L;
	private Integer id;
	private Date channingReviewDate;
	private String channingReviewer;
	private String channingReviewerCc;
	private String channingReviewerEmail;
	private String facultyMember;
	private Date facultyMemberApprovalDate;
	private String facultyMemberEmail;
	private String manuscriptId;
	private Date programReviewDate;
	private String programReviewer;
	private String programReviewerEmail;
	private String status;
	private Date submitDate;
	private Date techReviewDate;
	private String techReviewer;
	private String techReviewerEmail;
	private String userGroup;

	public Reviewinfo() {
	}

	public Reviewinfo(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	public Reviewinfo(Date channingReviewDate, String channingReviewer,
			String channingReviewerCc, String channingReviewerEmail,
			String facultyMember, Date facultyMemberApprovalDate,
			String facultyMemberEmail, String manuscriptId,
			Date programReviewDate, String programReviewer,
			String programReviewerEmail, String status, Date submitDate,
			Date techReviewDate, String techReviewer, String techReviewerEmail,
			String userGroup) {
		this.channingReviewDate = channingReviewDate;
		this.channingReviewer = channingReviewer;
		this.channingReviewerCc = channingReviewerCc;
		this.channingReviewerEmail = channingReviewerEmail;
		this.facultyMember = facultyMember;
		this.facultyMemberApprovalDate = facultyMemberApprovalDate;
		this.facultyMemberEmail = facultyMemberEmail;
		this.manuscriptId = manuscriptId;
		this.programReviewDate = programReviewDate;
		this.programReviewer = programReviewer;
		this.programReviewerEmail = programReviewerEmail;
		this.status = status;
		this.submitDate = submitDate;
		this.techReviewDate = techReviewDate;
		this.techReviewer = techReviewer;
		this.techReviewerEmail = techReviewerEmail;
		this.userGroup = userGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "channing_review_date", length = 19)
	public Date getChanningReviewDate() {
		return this.channingReviewDate;
	}

	public void setChanningReviewDate(Date channingReviewDate) {
		this.channingReviewDate = channingReviewDate;
	}

	@Column(name = "channing_reviewer")
	public String getChanningReviewer() {
		return this.channingReviewer;
	}

	public void setChanningReviewer(String channingReviewer) {
		this.channingReviewer = channingReviewer;
	}

	@Column(name = "channing_reviewer_cc")
	public String getChanningReviewerCc() {
		return this.channingReviewerCc;
	}

	public void setChanningReviewerCc(String channingReviewerCc) {
		this.channingReviewerCc = channingReviewerCc;
	}

	@Column(name = "channing_reviewer_email")
	public String getChanningReviewerEmail() {
		return this.channingReviewerEmail;
	}

	public void setChanningReviewerEmail(String channingReviewerEmail) {
		this.channingReviewerEmail = channingReviewerEmail;
	}

	@Column(name = "faculty_member")
	public String getFacultyMember() {
		return this.facultyMember;
	}

	public void setFacultyMember(String facultyMember) {
		this.facultyMember = facultyMember;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "faculty_member_approval_date", length = 19)
	public Date getFacultyMemberApprovalDate() {
		return this.facultyMemberApprovalDate;
	}

	public void setFacultyMemberApprovalDate(Date facultyMemberApprovalDate) {
		this.facultyMemberApprovalDate = facultyMemberApprovalDate;
	}

	@Column(name = "faculty_member_email")
	public String getFacultyMemberEmail() {
		return this.facultyMemberEmail;
	}

	public void setFacultyMemberEmail(String facultyMemberEmail) {
		this.facultyMemberEmail = facultyMemberEmail;
	}

	@Column(name = "manuscript_id", nullable = false)
	public String getManuscriptId() {
		return this.manuscriptId;
	}

	public void setManuscriptId(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "program_review_date", length = 19)
	public Date getProgramReviewDate() {
		return this.programReviewDate;
	}

	public void setProgramReviewDate(Date programReviewDate) {
		this.programReviewDate = programReviewDate;
	}

	@Column(name = "program_reviewer")
	public String getProgramReviewer() {
		return this.programReviewer;
	}

	public void setProgramReviewer(String programReviewer) {
		this.programReviewer = programReviewer;
	}

	@Column(name = "program_reviewer_email")
	public String getProgramReviewerEmail() {
		return this.programReviewerEmail;
	}

	public void setProgramReviewerEmail(String programReviewerEmail) {
		this.programReviewerEmail = programReviewerEmail;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_date", length = 19)
	public Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tech_review_date", length = 19)
	public Date getTechReviewDate() {
		return this.techReviewDate;
	}

	public void setTechReviewDate(Date techReviewDate) {
		this.techReviewDate = techReviewDate;
	}

	@Column(name = "tech_reviewer")
	public String getTechReviewer() {
		return this.techReviewer;
	}

	public void setTechReviewer(String techReviewer) {
		this.techReviewer = techReviewer;
	}

	@Column(name = "tech_reviewer_email")
	public String getTechReviewerEmail() {
		return this.techReviewerEmail;
	}

	public void setTechReviewerEmail(String techReviewerEmail) {
		this.techReviewerEmail = techReviewerEmail;
	}

	@Column(name = "user_group")
	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}

}
