package edu.harvard.channing.regepi.hibernate.test;
// default package
// Generated Oct 2, 2014 9:45:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "channingreview")
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5688675868767420590L;
	private Integer id;
	private String manuscriptId;
	private String status;
	private Date submitDate;
	private String userGroup;

	public Status() {
	}

	public Status(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	public Status(String manuscriptId, String status, Date submitDate,
			String userGroup) {
		this.manuscriptId = manuscriptId;
		this.status = status;
		this.submitDate = submitDate;
		this.userGroup = userGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "manuscript_id", nullable = false)
	public String getManuscriptId() {
		return this.manuscriptId;
	}

	public void setManuscriptId(String manuscriptId) {
		this.manuscriptId = manuscriptId;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_date", length = 19)
	public Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	@Column(name = "user_group")
	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}

}
